spring:
  cloud:
    gateway:
          routes:
            - id: Contact-service
              uri: http://localhost:8080
              predicates:
                - Path=/contacts/**
              filters:
#                - StripPrefix=1 # Removes /service1 from the path
                - AddRequestHeader=X-Gateway-Identifier, gateway-only # Adds a header
                - AddResponseHeader=X-Gateway-Identifier, gateway-only # Adds a header
            - id: Error-service
              uri: http://localhost:9090
              predicates:
                - Path=/errorcodes/**
              filters:
#                - StripPrefix=1 # Removes /service1 from the path
                - AddRequestHeader=X-Gateway-Identifier, gateway-only # Adds a header
                - AddResponseHeader=X-Gateway-Identifier, gateway-only # Adds a header
  application:
    name: CloudGateWay

server:
  port: 2000

management:
   endpoints:
      web:
        exposure:
          include: health, info
   endpoint:
      info:  
         enabled: true

info:
   app: 
     name: My Spring Boot Application
     description: An example Spring Boot application
     version: 1.0.0

logging:
   level:
     org.springframework.boot.actuate: DEBUG

